//! Dispute

use serde::{Deserialize, Serialize};

use crate::api::models::enums::versions::v20230925::{dispute_reason::DisputeReasonV20230925, dispute_state::DisputeStateV20230925, card_brand::CardBrandV20230925};

use super::{money::MoneyV20230925, disputed_payment::DisputedPaymentV20230925};

/// Represents a [dispute](https://developer.squareup.com/docs/disputes-api/overview) a cardholder initiated with their bank.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DisputeV20230925{
    /// The unique ID for this `Dispute`, generated by Square.
    ///
    /// Min Length 1 Max Length 40
    pub id: Option<String>,
    /// The disputed amount, which can be less than the total transaction amount. For instance, if multiple items were purchased but the cardholder only initiates a dispute over some of the items.
    pub amount_money: Option<MoneyV20230925>,
    /// The reason why the cardholder initiated the dispute.
    pub reason: Option<DisputeReasonV20230925>,
    /// The current state of this dispute.
    pub state: Option<DisputeStateV20230925>,
    /// The deadline by which the seller must respond to the dispute, in [RFC 3339 format](https://developer.squareup.com/docs/build-basics/common-data-types/working-with-dates).
    ///
    /// Min Length 1 Max Length 40
    pub due_at: Option<String>,
    /// The payment challenged in this dispute.
    pub disputed_payment: Option<DisputedPaymentV20230925>,
    /// The card brand used in the disputed payment.
    pub card_brand: Option<CardBrandV20230925>,
    /// Read only The timestamp when the dispute was created, in RFC 3339 format.
    ///
    /// Examples for January 25th, 2020 6:25:34pm Pacific Standard Time:
    ///
    /// UTC: 2020-01-26T02:25:34Z
    ///
    /// Pacific Standard Time with UTC offset: 2020-01-25T18:25:34-08:00
    ///
    /// Min Length 1 Max Length 40
    pub created_at: Option<String>,
    /// Read only The timestamp when the dispute was last updated, in RFC 3339 format.
    ///
    /// Examples for January 25th, 2020 6:25:34pm Pacific Standard Time:
    ///
    /// UTC: 2020-01-26T02:25:34Z
    ///
    /// Pacific Standard Time with UTC offset: 2020-01-25T18:25:34-08:00
    ///
    /// Min Length 1 Max Length 40
    pub updated_at: Option<String>,
    /// The ID of the dispute in the card brand system, generated by the card brand.
    ///
    /// Min Length 1 Max Length 40
    pub brand_dispute_id: Option<String>,
    /// The timestamp when the dispute was reported, in RFC 3339 format.
    ///
    /// Examples for January 25th, 2020 6:25:34pm Pacific Standard Time:
    ///
    /// UTC: 2020-01-26T02:25:34Z
    ///
    /// Pacific Standard Time with UTC offset: 2020-01-25T18:25:34-08:00
    ///
    /// Min Length 1 Max Length 40
    pub reported_at: Option<String>,
    /// The current version of the `Dispute`.
    pub version: Option<i32>,
    /// The ID of the location where the dispute originated.
    ///
    /// Min Length 1 Max Length 40
    pub location_id: Option<String>,

}
