//! PaymentRefund

use serde::{Deserialize, Serialize};

use super::{destination_details::DestinationDetailsV20230925, money::MoneyV20230925, processing_fee::ProcessingFeeV20230925};

/// Represents a refund of a payment made using Square.
///
/// Contains information about the original payment and the amount of money refunded.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentRefundV20230925 {
    /// The unique ID for this refund, generated by Square.
    ///
    /// Min Length 1 Max Length 255
    pub id: String,
    /// The refund's status:
    /// - `PENDING` - Awaiting approval.
    /// - `COMPLETED` - Successfully completed.
    /// - `REJECTED` - The refund was rejected.
    /// - `FAILED` - An error occurred.
    ///
    /// Max Length 50
    pub status: Option<String>,
    /// The location ID associated with the payment this refund is attached to.
    pub location_id: Option<String>,
    /// Read only Flag indicating whether or not the refund is linked to an existing payment in Square.
    pub unlinked: Option<bool>,
    /// The destination type for this refund.
    /// Current values include CARD, BANK_ACCOUNT, WALLET, BUY_NOW_PAY_LATER, CASH, and EXTERNAL.
    ///
    /// Max Length 50
    pub destination_type: Option<String>,
    /// Read only Contains information about the refund destination. This field is populated only if destination_id is defined in the RefundPayment request.
    pub destination_details: Option<DestinationDetailsV20230925>,
    /// The amount of money refunded. This amount is specified in the smallest denomination of the applicable currency (for example, US dollar amounts are specified in cents).
    pub amount_money: MoneyV20230925,
    /// The amount of money the application developer contributed to help cover the refunded amount. This amount is specified in the smallest denomination of the applicable currency (for example, US dollar amounts are specified in cents). For more information, see [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts).
    pub app_fee_money: Option<MoneyV20230925>,
    /// Processing fees and fee adjustments assessed by Square for this refund.
    pub processing_fee: Option<Vec<ProcessingFeeV20230925>>,
    /// The ID of the payment associated with this refund.
    ///
    /// Max Length 192
    pub payment_id: Option<String>,
    /// The ID of the order associated with the refund.
    ///
    /// Max Length 192
    pub order_id: Option<String>,
    /// The reason for the refund.
    ///
    /// Max Length 192
    pub reason: Option<String>,
    /// Read only The timestamp of when the refund was created, in RFC 3339 format.
    ///
    /// Examples for January 25th, 2020 6:25:34pm Pacific Standard Time:
    ///
    /// UTC: 2020-01-26T02:25:34Z
    ///
    /// Pacific Standard Time with UTC offset: 2020-01-25T18:25:34-08:00
    ///
    /// Max Length 32
    pub created_at: Option<String>,
    /// Read only The timestamp of when the refund was last updated, in RFC 3339 format.
    ///
    /// Examples for January 25th, 2020 6:25:34pm Pacific Standard Time:
    ///
    /// UTC: 2020-01-26T02:25:34Z
    ///
    /// Pacific Standard Time with UTC offset: 2020-01-25T18:25:34-08:00
    ///
    /// Max Length 32
    pub updated_at: Option<String>,
    /// Read only An optional ID of the team member associated with taking the payment.
    ///
    /// Max Length 192
    pub team_member_id: Option<String>,
}
