//! SaveCardOptions

use serde::{Deserialize, Serialize};

/// Describes save-card action fields.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SaveCardOptionsV20230925 {
    /// The square-assigned ID of the customer linked to the saved card.
    pub customer_id: String,
    /// The id of the created card-on-file.
    ///
    /// Max Length: 64
    pub card_id: Option<String>,
    /// An optional user-defined reference ID that can be used to associate this Card to another entity in an external system. For example, a customer ID generated by a third-party system.
    ///
    /// Max Length: 128
    pub reference_id: Option<String>,
}
