services:
  app:
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile
    privileged: true
    env_file:
      - .env
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    container_name: square-rust

volumes:
  cargo-cache:
  target-cache:
