//! CardForgottenEventCard

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CardForgottenEventCard {
    /// Read only Unique ID for this card. Generated by Square.
    /// Max Length 64
    pub id: Option<String>,
    /// The ID of a customer created using the Customers API associated with the card.
    pub customer_id: Option<String>,
    /// Indicates whether or not a card can be used for payments.
    pub enabled: Option<bool>,
    /// An optional user-defined reference ID that associates this card with another entity in an external system. For example, a customer ID from an external customer management system.
    /// Max Length 192
    pub reference_id: Option<String>,
    /// Current version number of the card. Increments with each card update. Requests to update an existing Card object will be rejected unless the version in the request matches the current version for the Card.
    pub version: Option<i64>,
    /// The ID of the merchant associated with the card.
    /// Max Length 64
    pub merchant_id: Option<String>,
}
