//! InventoryAdjustment

use serde::{Deserialize, Serialize};

/// Represents a change in state or quantity of product inventory at a particular time and location.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InventoryAdjustment {
    /// A unique ID generated by Square for the InventoryAdjustment.
    ///
    /// Max Length 100
    pub id: Option<String>,
    /// An optional ID provided by the application to tie the InventoryAdjustment to an external system.
    ///
    /// Max Length 255
    pub reference_id: Option<String>,
    /// The [inventory state](https://developer.squareup.com/reference/square/objects/InventoryState) of the related quantity of items before the adjustment.
    pub from_state: Option<InventoryState>,
    /// The [inventory state](https://developer.squareup.com/reference/square/objects/InventoryState) of the related quantity of items after the adjustment.
    pub to_state: Option<InventoryState>,
    /// The Square-generated ID of the [Location](https://developer.squareup.com/reference/square/objects/Location) where the related quantity of items is being tracked.
    ///
    /// Max Length 100
    pub location_id: Option<String>,
    /// The Square-generated ID of the [CatalogObject](https://developer.squareup.com/reference/square/objects/CatalogObject) being tracked.
    ///
    /// Max Length 100
    pub catalog_object_id: Option<String>,
    /// The [type](https://developer.squareup.com/reference/square/objects/CatalogObjectType) of the [CatalogObject](https://developer.squareup.com/reference/square/objects/CatalogObject) being tracked.
    ///
    /// The Inventory API supports setting and reading the "catalog_object_type": "ITEM_VARIATION" field value. In addition, it can also read the "catalog_object_type": "ITEM" field value that is set by the Square Restaurants app.
    ///
    /// Max Length 14
    pub catalog_object_type: Option<String>,
    /// The number of items affected by the adjustment as a decimal string. Can support up to 5 digits after the decimal point.
    ///
    /// Max Length 26
    pub quantity: Option<String>,
    /// Read only The total price paid for goods associated with the adjustment. Present if and only if to_state is SOLD. Always non-negative.
    pub total_price_money: Option<Money>,
    /// A client-generated RFC 3339-formatted timestamp that indicates when the inventory adjustment took place. For inventory adjustment updates, the occurred_at timestamp cannot be older than 24 hours or in the future relative to the time of the request.
    ///
    /// Examples for January 25th, 2020 6:25:34pm Pacific Standard Time:
    ///
    /// UTC: 2020-01-26T02:25:34Z
    ///
    /// Pacific Standard Time with UTC offset: 2020-01-25T18:25:34-08:00
    ///
    /// Max Length 34
    pub occurred_at: Option<String>,
    /// Read only An RFC 3339-formatted timestamp that indicates when the inventory adjustment is received.
    ///
    /// Examples for January 25th, 2020 6:25:34pm Pacific Standard Time:
    ///
    /// UTC: 2020-01-26T02:25:34Z
    ///
    /// Pacific Standard Time with UTC offset: 2020-01-25T18:25:34-08:00
    ///
    /// Max Length 34
    pub created_at: Option<String>,
    /// Read only Information about the application that caused the inventory adjustment.
    pub source: Option<SourceApplication>,
    /// The Square-generated ID of the [Employee](https://developer.squareup.com/reference/square/objects/Employee) responsible for the inventory adjustment.
    ///
    /// Max Length 100
    pub employee_id: Option<String>,
    /// The Square-generated ID of the [Team Member](https://developer.squareup.com/reference/square/objects/TeamMember) responsible for the inventory adjustment.
    ///
    /// Max Length 100
    pub team_member_id: Option<String>,
    /// Read only The Square-generated ID of the [Transaction](https://developer.squareup.com/reference/square/objects/Transaction) that caused the adjustment. Only relevant for payment-related state transitions.
    ///
    /// Max Length 255
    pub transaction_id: Option<String>,
    /// Read only The Square-generated ID of the [Refund](https://developer.squareup.com/reference/square/objects/Refund) that caused the adjustment. Only relevant for refund-related state transitions.
    ///
    /// Max Length 255
    pub refund_id: Option<String>,
    /// Read only The Square-generated ID of the purchase order that caused the adjustment. Only relevant for state transitions from the Square for Retail app.
    ///
    /// Max Length 100
    pub purchase_order_id: Option<String>,
    /// Read only The Square-generated ID of the goods receipt that caused the adjustment. Only relevant for state transitions from the Square for Retail app.
    ///
    /// Max Length 100
    pub goods_receipt_id: Option<String>,
    /// Read only An adjustment group bundling the related adjustments of item variations through stock conversions in a single inventory event.
    pub adjustment_group: Option<InventoryAdjustmentGroup>,
}
