//! TerminalCheckout

use serde::{Deserialize, Serialize};

/// Represents a checkout processed by the Square Terminal.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TerminalCheckout {
    /// Read only A unique ID for this TerminalCheckout.
    ///
    /// Min Length 10 Max Length 255
    pub id: Option<String>,
    /// The amount of money (including the tax amount) that the Square Terminal device should try to collect.
    pub amount_money: Money,
    /// An optional user-defined reference ID that can be used to associate this TerminalCheckout to another entity in an external system. For example, an order ID generated by a third-party shopping cart. The ID is also associated with any payments used to complete the checkout.
    ///
    /// Max Length 40
    pub reference_id: Option<String>,
    /// An optional note to associate with the checkout, as well as with any payments used to complete the checkout. Note: maximum 500 characters
    ///
    /// Max Length 500
    pub note: Option<String>,
    /// The reference to the Square order ID for the checkout request. Supported only in the US.
    pub order_id: Option<String>,
    /// Payment-specific options for the checkout request. Supported only in the US.
    pub payment_options: Option<PaymentOptions>,
    /// Options to control the display and behavior of the Square Terminal device.
    pub device_options: DeviceCheckoutOptions,
    /// Read only The status of the TerminalCheckout. Options: PENDING, IN_PROGRESS, CANCEL_REQUESTED, CANCELED, COMPLETED
    pub status: Option<String>,
    /// Read only The reason why TerminalCheckout is canceled. Present if the status is CANCELED.
    pub cancel_reason: Option<ActionCancelReason>,
    /// Read only A list of IDs for payments created by this TerminalCheckout.
    pub payment_ids: Option<Vec<String>>,
    /// Read only The time when the TerminalCheckout was created, as an RFC 3339 timestamp.
    ///
    /// Examples for January 25th, 2020 6:25:34pm Pacific Standard Time:
    ///
    /// UTC: 2020-01-26T02:25:34Z
    ///
    /// Pacific Standard Time with UTC offset: 2020-01-25T18:25:34-08:00
    pub created_at: Option<String>,
    /// Read only The time when the TerminalCheckout was last updated, as an RFC 3339 timestamp.
    ///
    /// Examples for January 25th, 2020 6:25:34pm Pacific Standard Time:
    ///
    /// UTC: 2020-01-26T02:25:34Z
    ///
    /// Pacific Standard Time with UTC offset: 2020-01-25T18:25:34-08:00
    pub updated_at: Option<String>,
    /// Read only The ID of the application that created the checkout.
    pub app_id: Option<String>,
    /// Read only The location of the device where the TerminalCheckout was directed.
    ///
    /// Max Length 64
    pub location_id: Option<String>,
    /// The type of payment the terminal should attempt to capture from. Defaults to CARD_PRESENT.
    pub payment_type: Option<CheckoutOptionsPaymentType>,
    /// An optional ID of the team member associated with creating the checkout.
    pub team_member_id: Option<String>,
    /// An optional ID of the customer associated with the checkout.
    pub customer_id: Option<String>,
    /// The amount the developer is taking as a fee for facilitating the payment on behalf of the seller.
    ///
    /// The amount cannot be more than 90% of the total amount of the payment.
    ///
    /// The amount must be specified in the smallest denomination of the applicable currency (for example, US dollar amounts are specified in cents). For more information, see [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts).
    ///
    /// The fee currency code must match the currency associated with the seller that is accepting the payment. The application must be from a developer account in the same country and using the same currency code as the seller.
    ///
    /// For more information about the application fee scenario, see [Take Payments and Collect Fees](https://developer.squareup.com/docs/payments-api/take-payments-and-collect-fees).
    ///
    /// To set this field, PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS OAuth permission is required. For more information, see [Permissions](https://developer.squareup.com/docs/payments-api/take-payments-and-collect-fees#permissions).
    ///
    /// Supported only in the US.
    pub app_fee_money: Option<Money>,
    /// Optional additional payment information to include on the customer's card statement as part of the statement description. This can be, for example, an invoice number, ticket number, or short description that uniquely identifies the purchase. Supported only in the US.
    ///
    /// Max Length 20
    pub statement_description_identifier: Option<String>,
    /// The amount designated as a tip, in addition to amount_money. This may only be set for a checkout that has tipping disabled (tip_settings.allow_tipping is false). Supported only in the US.
    pub tip_money: Option<Money>,
}
