//! LoyaltyEventSource Enum

use serde::{Deserialize, Serialize};

/// Defines whether the event was generated by the Square Point of Sale.
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum LoyaltyEventSourceV20230925 {
    /// The event is generated by the Square Point of Sale (POS).
    Square,
    /// The event is generated by something other than the Square Point of Sale that used the Loyalty API.
    LoyaltyApi,
}
