use crate::api::models::address::Address;
use crate::api::models::money::Money;
use crate::api::models::cash_details::CashDetails;
use crate::api::models::external_details::ExternalDetails;
use crate::api::models::customer_details::CustomerDetails;

pub struct CreatePaymentRequestV20230925 {
    /// The ID for the source of funds for this payment. This could be a payment token generated by the Web Payments SDK for any of its [supported methods](https://developer.squareup.com/docs/web-payments/overview#explore-payment-methods),
    /// including cards, bank transfers, Afterpay or Cash App Pay. If recording a payment that the seller received outside of Square, specify either "CASH" or "EXTERNAL".
    ///  For more information, see [Take Payments](https://developer.squareup.com/docs/payments-api/take-payments).
    /// Min Length 1
    pub source_id: String,
    /// A unique string that identifies this CreatePayment request. Keys can be any valid string but must be unique for every CreatePayment request.
    /// Note: The number of allowed characters might be less than the stated maximum, if multi-byte characters are used.
    /// For more information, see [Idempotency](https://developer.squareup.com/docs/working-with-apis/idempotency).
    /// Min Length 1, Max Length 45
    pub idenmpotency_key: String,
    pub amount_money: Option<Money>,
    pub tip_money: Option<Money>,
    pub app_fee_money: Option<Money>,
    pub delay_duration: Option<String>,
    pub delay_action: Option<String>,
    pub autocomplete: Option<bool>,
    pub order_id: Option<String>,
    pub customer_id: Option<String>,
    pub location_id: Option<String>,
    pub team_member_id: Option<String>,
    pub reference_id: Option<String>,
    pub verification_token: Option<String>,
    pub accept_partial_authorization: Option<bool>,
    pub buyer_email_address: Option<String>,
    pub billing_address: Option<Address>,
    pub shipping_address: Option<Address>,
    pub note: Option<String>,
    pub statement_description_identifier: Option<String>,
    pub cash_details: Option<CashDetails>,
    pub external_details: Option<ExternalDetails>,
    pub customer_details: Option<CustomerDetails>,
}

// response
// errors
// payment