name: Auto Tag Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-09-29
        override: true

    - name: Extract version from Cargo.toml
      run: echo "NEW_VERSION=$(grep '^version =' Cargo.toml | sed 's/version = //;s/\"//g')" >> $GITHUB_ENV

    - name: Get existing tags
      id: get_tags
      run: echo "::set-output name=tags::$(git tag)"

    - name: Check if tag exists
      id: check_tag
      run: echo "::set-output name=exists::$(echo '${{ steps.get_tags.outputs.tags }}' | grep -q -w v${{ env.NEW_VERSION }} && echo 'true' || echo 'false')"

    - name: Create and Push Git Tag
      if: steps.check_tag.outputs.exists == 'false'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag v${{ env.NEW_VERSION }}
        git push origin v${{ env.NEW_VERSION }}
